name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Node
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c483a26c91 # v4.2.0
      with:
        node-version: 20

    - name: Install Elm
      run: |
        npm install -g elm elm-test

    - name: Run Tests
      run: |
        elm-test

    - name: Build Elm App
      run: |
        elm make src/Main.elm --optimize --output=main.js

    - name: Setup Pages
      uses: actions/configure-pages@11b93f6ba9cc2b18420e6a3c631024345517f8a3 # v5.0.0

    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dee4629d9575 # v3.0.1
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
